services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
    env_file: .env
    environment:
      FRONTEND_DIR: /frontend
    restart: unless-stopped
    networks:
      - pg_projects

networks:
  pg_projects:
    name: pg_projects

